name: Check Broken Links

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies and build site
        run: |
          npm ci
          npm run build

      - name: Link Checker (Lychee)
        uses: lycheeverse/lychee-action@v2
        with:
          # Define o diretório raiz para resolver links locais e aceita o código HTTP 403
          args: >
            --verbose 
            --no-progress 
            --exclude-mail 
            --root-dir ./dist
            --accept 200..299,403
            --exclude '(linkedin\.com|twitter\.com|x\.com|make\.com)'
            './dist/**/*.html'
          fail: false